function(discover_headers HEADER_DIR OUT_HEADER_LIST)
    message(STATUS "searching for headers:")
    FILE(GLOB_RECURSE HEADER_LIST "${HEADER_DIR}/*.h")
    message(STATUS "out: " ${HEADER_LIST} " done.")
    include_directories(${HEADER_DIR})
    set(${OUT_HEADER_LIST} ${HEADER_LIST} PARENT_SCOPE)
endfunction()

function(discover_cpp SRC_DIR OUT_SRC_LIST)
    message(STATUS "searching for cpp src:")
    FILE(GLOB_RECURSE SRC_LIST "${SRC_DIR}/*.cpp")
    message(STATUS "out:" ${SRC_DIR} " done.")
    set(${OUT_SRC_LIST} ${SRC_LIST} PARENT_SCOPE)
endfunction()

function(discover_c SRC_DIR OUT_SRC_LIST)
    message(STATUS "searching for C src in : ${SRC_DIR}")
    FILE(GLOB_RECURSE SRC_LIST "${SRC_DIR}/*.c")
    message(STATUS "out:" ${SRC_DIR} " done.")
    set(${OUT_SRC_LIST} ${SRC_LIST} PARENT_SCOPE)
endfunction()

function(import_dirs IMPORTED_DIRS)
    foreach(DIR ${IMPORTED_DIRS})
      add_subdirectory(${DIR})
    endforeach()

    foreach(DIR ${IMPORTED_DIRS})
      include_directories(${DIR}/include)
    endforeach()
endfunction()
